### ISSUE TITLE
Olsrd-0.9.1 die unexpectly on Debian Wheezy

### ISSUE THREAD

**Issue by gabri94** [OLSR/olsrd#1]
Platform: Ubiquiti Edgerouter Lite (mips64)
Kernel: Linux ubnt 3.10.20-UBNT 
Libc: 2.13-38+deb7u8
Olsr : pre-0.9.1-git_564e1b1-hash_cdb27b6747bc38fef73115019dc168ab

The olsr daemon crash after some random time with this message:

```
*** glibc detected *** /usr/local/sbin/olsrd: realloc(): invalid next size: 0x004b6560 ***
Received signal Aborted - shutting down
Deleting all routes...

```
The gdb backtrace will follow soon.

**Comment by gabri94** [comment]
*** glibc detected *** /usr/local/sbin/olsrd: realloc(): invalid next size: 0x004cd7a8 ***
Program received signal SIGABRT, Aborted.
0x77e57b28 in raise () from /lib/mips-linux-gnu/libc.so.6
(gdb) bt
#0  0x77e57b28 in raise () from /lib/mips-linux-gnu/libc.so.6
#1  0x77e5cce0 in abort () from /lib/mips-linux-gnu/libc.so.6
#2  0x77e9a268 in ?? () from /lib/mips-linux-gnu/libc.so.6
warning: GDB can't find the start of the function at 0x77e9a266.

**Comment by fhuberts** [comment]
Unfortunately that backtrace is of little use.
Do show your config.

Is there a limitation on MIPS on the realloc size? Alignment limitation?

**Comment by gabri94** [comment]
```
root@ubnt:/home/ubnt# cat /etc/olsrd/olsrd.conf.netjson 
AllowNoInt yes
RtTable 111
RtTableDefault 112
FIBMetric "flat"
LinkQualityLevel 2
LinkQualityAlgorithm "etx_ff"
OlsrPort 698
Willingness 3
NatThreshold 1.0
MainIp 10.150.25.1
IpVersion 4

Hna4
{
		10.150.25.0 255.255.255.0
}
	
		
				
LoadPlugin "/usr/local/lib/olsrd_arprefresh.so.0.1"
{
}
				
LoadPlugin "/usr/local/lib/olsrd_nameservice.so.0.3"
{
	PlParam "name" "santaMarta"
	PlParam "suffix" ".nnx"
}
						
LoadPlugin "/usr/local/lib/olsrd_txtinfo.so.0.1"
{
	PlParam "accept" "0.0.0.0"
}
						
LoadPlugin "/usr/local/lib/olsrd_mdns.so.1.0.1"
{
	PlParam "NonOlsrIf" "br-lan"
	PlParam "TTL-Check" "1"
	PlParam "Network-ID" "1"
}
										
LoadPlugin "/usr/local/lib/olsrd_jsoninfo.so.0.0"
{
	PlParam "accept" "0.0.0.0"
 	PlParam "port" "2007"
}

LoadPlugin "/usr/local/lib/olsrd_netjson.so.1.0"
{
	PlParam "accept" "0.0.0.0"
	PlParam "port" "2005"
}
											
InterfaceDefaults
{
	Mode "mesh"
}
												
Interface "eth1.3"
{
}
												
Interface "eth1.4"
{
}

Interface "eth1.2"
{
}

Interface "eth1.5"
{

}	
```

**Comment by gabri94** [comment]
I can replicate the bug on Debian sid (unstable) with kernel 4.5.0-2 on my laptop.
I'll attach the backtrace.

**Comment by fhuberts** [comment]
I fixed that bug last week, upgrade to at least f52835c32c508229f2974f8404d21cb04fc0b5a1.

**Comment by fhuberts** [comment]
Sorry for not checking this bug, I thought it was unrealted but after seeing the sha again things fell into place.

If not fixed then do report back :-)
