### ISSUE TITLE
Update or migrate to new libgps versions required?

### ISSUE THREAD

**Issue by vchrizz** [OLSR/olsrd#105]
Since Debian11/bullseye (and also Ubuntu 20.04) the package libgps23 is not available anymore.
Thus  it is not possible to install olsrd-plugins 0.9.8 in those distributions (but olsrd 0.9.8 installed ok).

Instead since Debian11/bullseye the package libgps28 and since Ubuntu 20.04 the package libgps26 is available.

I guess there is a migration required, similar like [migrate to using bison 3.7.1](https://github.com/OLSR/olsrd/commit/be461986c6b3180837ad776a852be9ce22da56c0) ?

**Comment by PolynomialDivision** [comment]
Are you referencing to the already fixed issue in the master branch?
https://github.com/OLSR/olsrd/commit/79a28cdb4083b66c5d3a5f9c0d70dbdc86c0420c

**Comment by pmelange** [comment]
Perhaps @vchrizz means somthing similar to 35f4205052c80bc93e72d1826d393d489339f46d

**Comment by PolynomialDivision** [comment]
We finally have to make a new release containing all the fixes. :/ @fhuberts Could you maybe do that? :S

**Comment by vchrizz** [comment]
Sorry, it seems this is (again) some Debian specific "issue". It seems, depending on which Debian distribution the package is built, the according libgps package is required.

If the package is built in Debian9/stretch environment, libgps22 is required.
If the package is built in Debian10/buster environment, libgps23 is required.
On newer distributions newer libgps versions are required it seems.

So I try to build the package on recent Debian 11/bullseye, but there I run into another issue I am not sure if this is again Debian/bullseye specific:
(in Debian10/buster this worked without issues, it seems the only thing what changed, gcc is now using -ffile-prefix-map instead of -fdebug-prefix-map)
```
gcc -g -O2 -ffile-prefix-map=/build/olsrd-0.9.8=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -ggdb -I/build/olsrd-0.9.8/src -I/build/olsrd-0.9.8/lib -I/build/olsrd-0.9.8/lib/pud/nmealib/include -I/build/olsrd-0.9.8/lib/pud/wireformat/include  -DUSE_FPM -DDEBUG   -c -o src/cfgparser/olsrd_conf_checksum.o src/cfgparser/olsrd_conf_checksum.c
bison -d -o "src/cfgparser/oparse.c-tmp" "src/cfgparser/oparse.y"
sed	-e 's/register //' \
	-e '/^#line/s/src\/cfgparser\/oparse\.c-tmp/src\/cfgparser\/oparse\.c/' \
	< "src/cfgparser/oparse.c-tmp" >"src/cfgparser/oparse.c"
mv "src/cfgparser/oparse.h-tmp" "src/cfgparser/oparse.h"
rm -f "src/cfgparser/oparse.c-tmp" "src/cfgparser/oparse.h-tmp"
gcc -g -O2 -ffile-prefix-map=/build/olsrd-0.9.8=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -ggdb -I/build/olsrd-0.9.8/src -I/build/olsrd-0.9.8/lib -I/build/olsrd-0.9.8/lib/pud/nmealib/include -I/build/olsrd-0.9.8/lib/pud/wireformat/include  -DUSE_FPM -DDEBUG   -c -o src/cfgparser/oparse.o src/cfgparser/oparse.c
src/cfgparser/oparse.c:265:10: fatal error: oparse.h-tmp: No such file or directory
  265 | #include "oparse.h-tmp"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```
