### ISSUE TITLE
AREDN network storms: What they look like, how they happen, and how to prevent them

### ISSUE THREAD

**Issue by aanon4** [OLSR/olsrd#106]
Network storms are the result of the OLSR demon on nodes restarting. A restart randomly resets the sequence number that will be used for new messages. Under certain circumstances these new sequence numbered messages can interact with old messages from the same source which are still in the network and create a message storm. The combined old and new messages confuse the deduplication code so that messages will always appear new, regardless of how many times a node received them, and will always be duplicated to their neighbors. This will continue until all copies of messages time-to-live expires on all nodes.

Full explanation and proposed solutions can be found here: https://docs.google.com/document/d/1OgURb2O36lWF518dKydJLBEEUTYt7khRTVzX8QChwqw/edit?usp=sharing

**Comment by storchi** [comment]
great work. thanks

**Comment by HRogge** [comment]
Maybe you want to take a look at the deduplication code in OLSRv2 too... I think it has a few more heuristics than the old one.
https://github.com/OLSR/OONF/blob/master/src/base/oonf_duplicate_set.c

**Comment by bittorf** [comment]
wow, that reminds me on old headaches - thanks a lot for finding the underlying issue!

**Comment by HRogge** [comment]
And its not only the sequence number, it can happen with the AnswerSet-number too...

**Comment by HRogge** [comment]
The sequence number handling code of (my) OLSRv2 implementation handles a jump in the sequence number by counting continuous sequences of "very old" numbers without any new ones... and triggers a "reset" in the duplication code after a while. Unfortunately this doesn't help with OLSRv1 and OLSRv2 ANSN, because they don't necessarily increase all the time (but in practice they do).

**Comment by mathisono** [comment]
Henning is  "The sequence number handling code of (my) OLSRv2 " in the
current release code?
Would it be safe to say that If ARDEN stopped using the old  OLSRv1 and
used  OLSRv2 we would stop having paralyzing storms on our networks?

**Comment by aanon4** [comment]
I've submitted a downstream pull request for AREDN only (https://github.com/aredn/aredn_packages/pull/5)

**Comment by mathiashro** [comment]
Hi @PolynomialDivision , should we take over some patches here?
