### ISSUE TITLE
OLSR Mailinglist Down

### ISSUE THREAD

**Issue by PolynomialDivision** [OLSR/olsrd#108]
Hey, the olsr.org mailinglist is down. @fhuberts @HRogge ?

**Comment by pocki80** [comment]
Sorry, still not fixed. I tried to contact admin address I found from whois query.

**Comment by aaronkaplan** [comment]
problem is being fixed...

**Comment by aaronkaplan** [comment]
I have to add: the current Funkfeuer team changed the IP address of the server without upfront notice. I think this should not happen in the future.... It's uncomfortable to always clean after unannounced changes.

**Comment by fhuberts** [comment]
@aaronkaplan Can you please remove me as admin there, I'm still getting bounce notifications

**Comment by aaronkaplan** [comment]
@fhuberts yes, as soon as it points to the right IP address again. Sorry about that.

**Comment by pocki80** [comment]
IP is correct now. Operation should be back to normal.
Thanks @aaronkaplan for help. Sorry for all that inconvenience.

**Comment by aaronkaplan** [comment]
@fhuberts removed you (the hoopie thing, right?)

**Comment by fhuberts** [comment]
yep, tnx!

**Comment by pocki80** [comment]
I think we can close this ticket. 
Issue is solved.
