### ISSUE TITLE
supporting gpsd 3.25

### ISSUE THREAD

**Issue by chenrui333** [OLSR/olsrd#118]
The `fixsource_t` definition got changed in the [gpsd 3.25 release](https://github.com/ntpsec/gpsd/commit/fde36494daa6eaaba7c366f13a74a331f2054648)

```diff
-/* describe a data source */
-struct fixsource_t {
-    char spec[PATH_MAX]; /* working space, will be modified */
-    char *server; /* pointer into spec field */
-    char *port; /* pointer into spec field */
-    char *device; /* pointer into spec field */
-};
+ // describe a gpsd source
+ struct fixsource_t
+ {
+     char spec[512];               // original string
+     const char *server;           // server name, maybe IP
+     const char *server_ip;        // server IP as string, maybe IPv4 or IPv6
+     const char *port;
+     const char *device;
+ };
```

also the file got moved from gpsdclient.h into gps.h, https://github.com/ntpsec/gpsd/commit/35fe48835da07cb1045e404aef0a582c04fd8da1

**Comment by mathiashro** [comment]
Hello @chenrui333, thank you for providing insights about the related gpsd changes. I've someone would provide a PR would be great. 

From my understanding no current OLSRd community member are actively using gpsd these days (I might not have the full picture).

**Comment by chenrui333** [comment]
let me see if I can help here. Thanks @mathiashro for the reply.
