### ISSUE TITLE
LEDE fails to build with "missing libcrypto.so.1.0.0"

### ISSUE THREAD

**Issue by SvenRoederer** [OLSR/olsrd#13]
just tried to build d2446672fb8a18868f1ddae6d7320ab86756d83d  on LEDE and packaging fails with 
> install -d -m0755 /mnt/hosts/build/src/openwrt/freifunk/lede/lede/build_dir/target-i386_pentium4_musl-1.1.15/olsrd-20170104/ipkg-i386_pentium4/olsrd/etc/hotplug.d/iface
install -m0755 ./files/olsrd.hotplug.sh /mnt/hosts/build/src/openwrt/freifunk/lede/lede/build_dir/target-i386_pentium4_musl-1.1.15/olsrd-20170104/ipkg-i386_pentium4/olsrd/etc/hotplug.d/iface/50-olsrd
find /mnt/hosts/build/src/openwrt/freifunk/lede/lede/build_dir/target-i386_pentium4_musl-1.1.15/olsrd-20170104/ipkg-i386_pentium4/olsrd -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package olsrd is missing dependencies for the following libraries:
libcrypto.so.1.0.0
Makefile:295: recipe for target '/mnt/hosts/build/src/openwrt/freifunk/lede/lede/bin/packages/i386_pentium4/routing/olsrd_20170104-463463d66b2fe8a1662ecd5f1687ed237da33e78_i386_pentium4.ipk' failed

It seems to be one of the commits from 4. Jan 2017 (6c50a722c0ad3f5fa29a4725c632803c0dc59d31 ... 463463d66b2fe8a1662ecd5f1687ed237da33e78)

**Comment by fhuberts** [comment]
You need openssl-devel.
Or use make -DNOCONFIGCHECKSUM=1
See 1130cbf9146502d56c135081af7f5d1a5b605d09

**Comment by SvenRoederer** [comment]
conf: calculate the checksum over the effective configuration (1130cbf9146502d56c135081af7f5d1a5b605d09) is causing this
