### ISSUE TITLE
rename option "sighup-file" to "writefiles_interval"

### ISSUE THREAD

**Issue by SvenRoederer** [OLSR/olsrd#15]
I just wonder if it would be more consistent to name this new parameter "writefiles_interval", as it affects the interval when following files are written:
- resolve-file
- hosts-file
- services-file
- latlon-file

referencing to commit (https://github.com/OLSR/olsrd/blob/9a0d5db6af787ee7f6d5f2597548542172d6cd1d/lib/nameservice/src/nameservice.c#L544)

**Comment by fhuberts** [comment]
AFAIK there is no consensus between you guys (in the other issue), so please first have that.
Otherwise there'll be commit after commit on this.

**Comment by SvenRoederer** [comment]
@booo so I'll rename it spoken yesterday, then we can integrate the new option into openwrt-routing.
Maybe the option should named "filewrite_interval", which I prefer (now).

**Comment by bittorf** [comment]
@SvenRoederer - so if this is only done/an issue on theOpenWrt/LEDE-side, just close this ticket

**Comment by booo** [comment]
@SvenRoederer I don't care. I do think the current name is not too bad because it references to the sighup-pid-file which creates kind of the right context. If the name is "filewrite_interval" you only get the context if you read the code.

**Comment by fhuberts** [comment]
fixed by https://github.com/OLSR/olsrd/pull/16
