### ISSUE TITLE
folder "openwrt" vs. openwrt-routing-feed

### ISSUE THREAD

**Issue by SvenRoederer** [OLSR/olsrd#19]
I just saw that the openwrt folder and found a lot of files also in the official openwrt-routing-feed.

So I wonder if it might be a good idea, to rely only on the routing-feed for OpenWrt-packages. This seems to be better maintained and used by more ppl.

In addition, the currently given feed-URL here is broken, as of the missing branch "stable"

**Comment by fhuberts** [comment]
I'm fine with someone (you?) from the OpenWRT/LEDE camp taking ownership of this directory/aspect.

@HRogge WDYT?

**Comment by HRogge** [comment]
On Sun, Jan 15, 2017 at 4:13 PM, Ferry Huberts <notifications@github.com>
wrote:

> I'm fine with someone (you?) from the OpenWRT/LEDE camp taking ownership
> of this directory/aspect.
>
> @HRogge <https://github.com/HRogge> WDYT?
>

Yes, would be nice to have the same person who updates the Routing Feed
also updates the directory in the Olsrd repository... that keeps things in
sync.

(reminds me that I have to check if I need to update the /openwrt directory
for OONF)

Henning

**Comment by bittorf** [comment]
ok, will take care of this...

**Comment by fhuberts** [comment]
thanks Basti!
Looking forward to your PRs :-)

**Comment by SvenRoederer** [comment]
I was also thinking of the option to drop this director here. 
The @openwrt-routing seems more up to date and used everywhere.

**Comment by HRogge** [comment]
On Thu, Jan 19, 2017 at 11:33 PM, Sven Roederer <notifications@github.com>
wrote:

> I was also thinking of the option to drop this director here.
> The @openwrt-routing <https://github.com/openwrt-routing> seems more up
> to date and used everywhere.
>
Same situation for Olsrd2...

I push OpenWRT scripts for released versions to openwrt-routing... but you
can built a "the current commit!" OpenWRT package with the /openwrt
repository in the OONF git itself, which can be very useful for testing new
stuff.

Henning

**Comment by fhuberts** [comment]
Guys, shall we remove the openwrt stuff in the olsrd tree?
I did a few PRs on openwrt-routing already.

**Comment by bittorf** [comment]
still on my ToDo-list...please wait some days...

**Comment by PolynomialDivision** [comment]
I think I will drop this folder.
