### ISSUE TITLE
LinkQualityMult doesnt work anymore

### ISSUE THREAD

**Issue by FreifunkUFO** [OLSR/olsrd#22]
LinkQualityMult values not working anymore.

tested with olsr v.0.9.5 and v.0.9.6
it was working at least with olsr v.0.9.0.3

details: see olsr-dev mailinglist

**Comment by fhuberts** [comment]
Please bisect the problem and let us know

**Comment by fhuberts** [comment]
Fixed on master (ba72b36e5a27c35dfc5bd626e1f1a3ec0c5941cb) and release branch (7a1f4de8f7e1ac3c1ed72d1539b4fb75c4aa8549).

2 hours to bisect, 1 second to fix...
