### ISSUE TITLE
Kills itself after sometimw

### ISSUE THREAD

**Issue by AbhishekUoR** [OLSR/olsrd#23]
I am using Mininet emulator wherein there are stations in multiple LAN AND I want to route 2 stations which are in different LAN.I am able to do that using olsrd2_static when I "xterm" to that station.But when I try to write same command within the script ,the olsrd2_static works fine bute after sometime it stops.

**Comment by fhuberts** [comment]
olsrd v2 issues must be filed here: https://github.com/OLSR/OONF/issues
