### ISSUE TITLE
olsr 0.9.6.2 txtinfo plugin 1.1 contexts are recognized by first 3 letters only

### ISSUE THREAD

**Issue by vchrizz** [OLSR/olsrd#42]
using txtinfo 1.1 a 404 error is returned when using /neigh or /link or /topo
but using /nei or /lin or /top the expected information is returned.

**Comment by fhuberts** [comment]
correct.
this was changed in release 0.9.5, see the CHANGELOG file, line 153 (file on master)

**Comment by vchrizz** [comment]
ok, thanks for the hint.
just a sidenote, this howto should then be updated: http://www.olsr.org/?q=txtinfo_plugin
