### ISSUE TITLE
Homepage says 0.9.0.3 is current release

### ISSUE THREAD

**Issue by ilovezfs** [OLSR/olsrd#48]
http://www.olsr.org/mediawiki/index.php/Releases

This seems to contradict the GitHub repo which says 0.9.6.2 is the latest.

And then in http://www.olsr.org/releases/0.9 the greatest version available is 0.9.6.1.

So which of the following is the latest release
0.9.0.3
0.9.6.1
0.9.6.2
something else

**Comment by fhuberts** [comment]
0962 is latest.
our server is 'ill' and needs to be repaired.
you can also use master, it's very stable
