### ISSUE TITLE
Plugin: drop gw HNA's

### ISSUE THREAD

**Issue by pmelange** [OLSR/olsrd#58]
In the freifunk-berlin network we have set up a way to allow mesh islands to mesh with the main mesh network though a vpn.  One of the features we find necessary is that gw HNA's are __not__ passed trough the vpn.  To do this, in the past, we have used a hack in hns_set.c.  Now it has been rewritten as a plugin.

My question to the OLSR dev crew is: should I submit the patch to the main OLSR branch?  Is anyone interested in using this plugin?

[drophna plugin](/freifunk-berlin/olsrd/tree/drophna_plugin)

**Comment by fhuberts** [comment]
patches welcome, but first please clean it up before submitting.

**Comment by pmelange** [comment]
I've cleaned it up, I hope.  Would you mind taking a look and suggesting further changes?

**Comment by fhuberts** [comment]
make it a PR
