### ISSUE TITLE
no httpheaders in infoplugins

### ISSUE THREAD

**Issue by pocki80** [OLSR/olsrd#69]
I tested new txtinfo (1.1) and see no http-headers, nor when requested by url (localhost:2006/http/ver), neigher when activated by plugin-parameter "httpheaders".

```
ubnt@wehr-router:~$ curl -I localhost:2006/http/ver
error: 404 Not Found

ubnt@wehr-router:~$ curl localhost:2006/http/ver
Version: olsr.org - pre-0.9.7-git_a24e20a-hash_3d83b56712d547acaa693fc988197192

```

**Comment by fhuberts** [comment]
works for me
{{{
$ curl -i localhost:2006/http/ver
HTTP/1.1 200 OK
Date: Tue, 05 Mar 2019 17:34:07 GMT
Server: OLSRD TXTINFO
Connection: close
Content-Type: text/plain; charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Accept, Origin, X-Requested-With
Access-Control-Max-Age: 1728000
Content-Length: 82          
Cache-Control: no-cache

Version: olsr.org - pre-0.9.7-git_c8f8d828-hash_96738a1df4397fb43ba278e517482018
}}}

'-I' not not the right option to use.

**Comment by pocki80** [comment]
I see. So,
'curl -i' requests "GET /http/ver HTTP/1.1" whereas
'curl -I' requests "HEAD /http/ver HTTP/1.1" which fails with the response

```
error: 404 Not Found
```
what means to me that the control method "HEAD" is not implemented. 
Closed :-)
