### ISSUE TITLE
gpsd v3.19's function gps_read() has changed causing olsrd to fail

### ISSUE THREAD

**Issue by pmelange** [OLSR/olsrd#74]
Currently there is a PR to upgrade gprsd to version 3.19 in the master branch of openwrt (https://github.com/openwrt/packages/pull/9588).  With the upgrade from 3.17 to 3.19 the function call gps_read() has changed from 

``` gps_read(struct gps_data_t *gpsdata)```
to
``` gps_read(struct gps_data_t *, char *message, int message_len)```

--

for a bit more background, openwrt has migrated to python3 (https://github.com/openwrt/openwrt/commit/316c8b5503e54cdb3ee5bd3b5d81a3b7dd139294) and therefore the upgrade from gpsd v3.17 to v3.19 is necessary.

in libgps_core.c, the function has the following comments:
```
/* read from a gpsd connection
 *
 * parameters:
 *    gps_data_t *gpsdata   -- structure for GPS data
 *    char *message         -- NULL, or optional buffer for received JSON
 *    int message_len       -- zero, or sizeof(message)
 */
int gps_read(struct gps_data_t *gpsdata CONDITIONALLY_UNUSED,
             char *message, int message_len)
```

There is already a patch written for OLSRd to make the required changes https://github.com/openwrt-routing/packages/pull/490

**Comment by fhuberts** [comment]
already fixed by 35f4205052c80bc93e72d1826d393d489339f46d on master
