### ISSUE TITLE
olsrd fails assert(multi_gateway_mode())

### ISSUE THREAD

**Issue by vanmierlo** [OLSR/olsrd#8]
Hi,

We very regularly experience olsrd to crash on a failed assertion in gateway.c:2371.
Attached are the config, the tcpdump, the gdb backtrace and the debug output.

[gdb.txt](https://github.com/OLSR/olsrd/files/624827/gdb.txt)
[run.txt](https://github.com/OLSR/olsrd/files/624828/run.txt)
[tcpdump.txt](https://github.com/OLSR/olsrd/files/624830/tcpdump.txt)
[olsrd.conf.txt](https://github.com/OLSR/olsrd/files/624834/olsrd.conf.txt)

This is on a Raspberry Pi 3 onboard wlan and with Raspbian 4.9 kernel.

If you need any more information to help get this fixed, please ask.

Maarten

**Comment by fhuberts** [comment]
olsrd version + sha1 + git sha

try on master as well

**Comment by vanmierlo** [comment]
Sorry. On last weeks release 0.9.5.

**Comment by fhuberts** [comment]
please try the branch sgw-fix and report back

**Comment by vanmierlo** [comment]
Thanks for the ultra-fast reply! We're sorry that it took us more time to find a moment to test it. But it certainly seems to fix the problem. We can now run both the smart and dynamic gateway functionality. It's been running for an hour now without crashes.

**Comment by fhuberts** [comment]
merged onto release-0.9.5 and master branches
