### ISSUE TITLE
gpsdclient.c:373:20: error: 'struct gps_fix_t' has no member named 'status'; 

### ISSUE THREAD

**Issue by zhaochengwei** [OLSR/olsrd#88]
## content
[CC] src/gpsdclient.c
src/gpsdclient.c: In function 'nmeaInfoFromGpsd':
src/gpsdclient.c:373:20: error: 'struct gps_fix_t' has no member named 'status'; did you mean 'datum'?
   if (gpsdata->fix.status == STATUS_NO_FIX) {
                    ^~~~~~
                    datum
../../Makefile.inc:357: recipe for target 'src/gpsdclient.o' failed
make[5]: *** [src/gpsdclient.o] Error 1
make[5]: Leaving directory '/home/douding/develop/lede/build_dir/target-x86_64_musl/olsrd-2020-06-18-84400e5c/lib/pud'

**Comment by decke** [comment]
gpsd 3.20 support was committed in https://github.com/OLSR/olsrd/commit/757b407ccdabf388c56d48745c4f8a14b7390967 and builds fine for me. So this issue can be closed I think.

**Comment by mathiashro** [comment]
Closing case as per comment and commit.

**Comment by decke** [comment]
I can reproduce this build issue now but only with gpsd 3.21

```
[CC] src/gpsdclient.c
src/gpsdclient.c: In function 'nmeaInfoFromGpsd':
src/gpsdclient.c:373:14: error: 'struct gps_data_t' has no member named 'status'
  373 |   if (gpsdata->status == STATUS_NO_FIX) {
      |              ^~
make[1]: *** [../../Makefile.inc:358: src/gpsdclient.o] Error 1
make[1]: Leaving directory '/home/decke/aports/olsrd/src/olsrd-0.9.8/lib/pud'
make: *** [Makefile:252: libs] Error 2
```
