### ISSUE TITLE
olsr.org - 0.9.8-git_0000000-hash_10144e50aca230a4127a3772519ad24e detaching from the current process...

### ISSUE THREAD

**Issue by bullr** [OLSR/olsrd#89]
I am testing a new emane installation on on Ubuntu 20 server, and while running through the [emane-tutorials](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-0) I am noticing that the olsrd process is terminating right after it initially loads on each emane node, which in tern causes the olsrlinkviewer to not display any links between the nodes or gps information.  I have not had this issue on previous installs using CentOS7, or older versions of Debian.  I have tried using both the latest GIT sources as well as the most recent release version in the wiki (0.9.8).  The output below is for 0.9.8, but is the same on the latest github sources.

```
sudo olsrd -f routing1.conf

 *** olsr.org - 0.9.8-git_0000000-hash_10144e50aca230a4127a3772519ad24e ***
 http://www.olsr.org

Parsing file: "routing1.conf"
Debug level: 0
IpVersion: 4
Lock file /usr/local/src/emane-tutorial/0/persist/1/var/run/olsrd.lock
Clear screen enabled
Link quality aging factor 0.200000
setting ifs_in_curr_cfg = 0
	HELLO interval: 1.00
	HELLO validity: 5.00
Plugin: 
Plugin param key:"accept" val: "0.0.0.0"
Plugin: olsrd_bmf.so.1.7.0
Plugin param key:"DoLocalBroadcast" val: "no"
Plugin param key:"CapturePacketsOnOlsrInterfaces" val: "no"
Plugin param key:"BmfMechanism" val: "Broadcast"
Plugin param key:"NonOlsrIf" val: "eth2"
Plugin param key:"FanOutLimit" val: "0"
Plugin param key:"BroadcastRetransmitCount" val: "1"
	IPv4 broadcast/multicast : AUTO
	Mode           : mesh
	IPv6 multicast           : ::
	HELLO emission/validity  : 1.00 (d)/5.00 (d)
	TC emission/validity     : 0.00/0.00
	MID emission/validity    : 0.00/0.00
	HNA emission/validity    : 0.00/0.00
	Autodetect changes       : no
	IPv4 broadcast/multicast : AUTO
	Mode           : mesh
	IPv6 multicast           : ::
	HELLO emission/validity  : 1.00 (d)/5.00 (d)
	TC emission/validity     : 0.00/0.00
	MID emission/validity    : 0.00/0.00
	HNA emission/validity    : 0.00/0.00
	Autodetect changes       : no

olsr.org - 0.9.8-git_0000000-hash_10144e50aca230a4127a3772519ad24e detaching from the current process...
```

And the olsrd process does not show up in the process list:

```
ps -ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 init
      8 ?        Ss     0:00 sshd: /usr/sbin/sshd -o PidFile=/usr/local/src/emane-tutorial/0/persist/2/var/run/ssh.pid [listener] 0 of 10-100 startups
      9 ?        Ss     0:00 sshd: me [priv]
     63 ?        R      0:00 sshd: me@pts/1
     64 pts/1    Ss     0:00 -bash
     82 ?        Ssl    0:00 emane platform2.xml -r -d -l 3 -f persist/2/var/log/emane.log
    109 pts/1    R+     0:00 ps -ax

```

**Comment by bullr** [comment]
After running with a higher debug level I found it was having issues finding certain libraries which never got compiled.  After reviewing the Makefile I saw an option for build_all and install_all which took care of compiling and installing the missing libraries that were causing the service to crash.

**Comment by HRogge** [comment]
"build_all" and "install_all" are compiling not only the core code but also all plugins...

**Comment by bullr** [comment]
Yes my issue was the emane tuturial was expecting certian plugins to be loaded and it was not reporting that they were not available until I increased the debug level to 9. The olsrd process still does not persist after running with the plugins in place without increasing the debug level above 0.  However this seems to be specific to the emane configs rather than olsrd.  Thanks for your response, this issue can be closed.

**Comment by sanjayjaiman** [comment]
Hello,
Could you please the emane config changes you made to make this work.  Thanks in advance.
Sanjay
