### ISSUE TITLE
Cannot get hops to show using traceroute - Running on Raspberry Pi

### ISSUE THREAD

**Issue by ghazi98** [OLSR/olsrd#90]
Hi there, I have OLSR version 0.6.6.2 running on a raspberry Pi B+, on Raspian Jessie Lite OS. I have 4 nodes running OLSR and everything seems to work fine but i cannot get hops to show when using traceroute command. Is this because the raspberry pi's are placed close together? 

In originators section it does show all my nodes, and when doing a traceroute from my primary node (first node) to my end node (last node), traceroute or ping shows no hops, it looks like the packet is sent directly to the end node without being routed through nodes 2 and nodes 3. Any help is appreciated! thanks

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/61443806/117761535-9aa29580-b27b-11eb-9837-3478264fc29b.png)
![117662679-edd10580-b1f3-11eb-9022-4a135ba7d59d](https://user-images.githubusercontent.com/61443806/117761584-b312b000-b27b-11eb-92da-cb921f8f5029.png)
![IMG_5202](https://user-images.githubusercontent.com/61443806/117762146-ae9ac700-b27c-11eb-804c-afc2a6202a9c.jpg)

**Comment by fhuberts** [comment]
All nodes are direct neighbours, so the packet is sent directly.

**Comment by ghazi98** [comment]
That is weird, because looking at this image I found off an academic research, they were able to perform a traceroute command, and recieve hop data? Is there anyway to get a similar output to what is shown below? 

<img width="328" alt="Screen Shot 2021-05-11 at 8 19 45 PM" src="https://user-images.githubusercontent.com/61443806/117783230-76a07d80-b296-11eb-876e-676822adf202.png">

**Comment by fhuberts** [comment]
place them so far apart that you get what you want, or add firewalling to enforce the route
